<?php 

/* module that keep all modules */

$module_array = array();

	/* page module */
	$module_array['0']="content";
	$module_array['1']="register";

	
	$module_array['9']="logout";

	$module_array['404']="error";



$shared_module_array = array();
	/* shared module */
	$shared_module_array['1000']="error";
	$shared_module_array['1001']="jumbo";
	$shared_module_array['1002']="news";
	$shared_module_array['1003']="gallery";
	$shared_module_array['1004']="panel";




